name: Pull Request Action Test

on:
  pull_request:
    types: [opened, reopened]

jobs:
  echoey:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Azure Machine Learning job
      run: |
        echo 'Will add more magico rico code checks here in next spicy challenge'
    
  call-workflow:
    uses: harveyhwm/mslearn-mlops/.github/workflows/04-code-checks.yml@main
    with:
      linting-path: 'src/model'
      testing-path: 'tests/test_train.py'