name: Code checks

on:
  workflow_call:
    inputs:
      linting-path:
        required: true
        type: string
      testing-path:
        required: true
        type: string

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Install PyTest
      run: |
        python -m pip install pytest
    - name: Run linting tests
      run: | 
        flake8 ${{ inputs.linting-path }}
    - name: Run unit tests
      run: | 
        pytest ${{ inputs.testing-path }}