name: Deploy Latest Version of Model to Managed Endpoint

on:
  workflow_dispatch:

jobs:


  deploy:
    needs: endpoint
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Deploy Azure ML Job
      run: |
        az ml online-deployment create --name credit-risk-deployment-1 --endpoint credit-risk-endpoint-1 -g recursos_magicos -w hmmlw2 -f src/job-deploy.yml --all-traffic --debug